### ISSUE TITLE
关于作业？

### ISSUE THREAD

**Issue by igo312** [wjbKimberly/cs231n_spring_2017_assignment#1]
你好，看了视频而来，请问实际作业也其实只是调用CS231而不是自己造轮子么？

**Comment by wjbKimberly** [comment]
斯坦福的网课作业中给予完整的课程练习，作业中也有自己调参尝试得到更好结果的部分。
由于学习这门课的人大多数是刚刚入门计算机视觉和深度学习，可以在完成作业，对框架熟悉后参与kaggle的比赛巩固知识。
